#!/usr/bin/env bash
set -euo pipefail

cd /root/savant-runtime

./BUILD_SAVANT_FS_COMPILER_PASS_01.sh
./BUILD_SAVANT_FS_COMPILER_PASS_02.sh
./BUILD_SAVANT_FS_COMPILER_PASS_03.sh
./BUILD_SAVANT_FS_COMPILER_PASS_04.sh
./BUILD_SAVANT_FS_COMPILER_PASS_05.sh
./BUILD_SAVANT_FS_COMPILER_GRAPH_DB.sh
./INGEST_FS_COMPILER_PASSES_TO_DB.sh
./BUILD_SAVANT_FS_COMPILER_PASS_06_PY_IMPORTS.sh
