#!/usr/bin/env bash
set -euo pipefail

cd /root/savant-runtime

echo "=== FAST NON-MOVE AUDIT ==="

./REBUILD_FS_COMPILER_DB_DIRECT.sh
./BUILD_SAVANT_FS_COMPILER_PASS_06_PY_IMPORTS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_07_SHELL_DEPS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_08_RUNTIME_LAUNCHERS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_09_SYMLINKS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_10_DUPLICATES.sh

echo "[OK] fast audit complete"
