#!/usr/bin/env bash
set -euo pipefail

cd /root/savant-runtime

./REBUILD_FS_COMPILER_DB_DIRECT.sh
./BUILD_SAVANT_FS_COMPILER_PASS_06_PY_IMPORTS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_07_SHELL_DEPS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_08_RUNTIME_LAUNCHERS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_09_SYMLINKS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_10_DUPLICATES.sh
./BUILD_SAVANT_FS_COMPILER_PASS_11_CANONICAL_PATHS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_16_TEXT_CONFIG_REFS.sh
./BUILD_SAVANT_FS_COMPILER_PASS_17_COMPILE_AUDIT.sh
./BUILD_SAVANT_FS_COMPILER_PASS_12_MOVE_CANDIDATES.sh
./BUILD_SAVANT_FS_COMPILER_PASS_13_SIMULATE_MOVES.sh
./BUILD_SAVANT_FS_COMPILER_PASS_14_VALIDATE_SIMULATION.sh
./BUILD_SAVANT_FS_COMPILER_PASS_15_EXECUTION_PLAN.sh
./BUILD_SAVANT_FS_COMPILER_PASS_18_HARD_SAFETY_GATE.sh
./REPORT_FS_COMPILER_HARD_BLOCKERS.sh
./REPORT_FS_COMPILER_MOVE_READINESS.sh

echo
echo "[OK] Full compiler audit complete. No files moved."
